parameters:
#    d_lauritz_forum_pages.example.class: DLauritz\Forum\PagesBundle\Example

services:
#    d_lauritz_forum_pages.example:
#        class: %d_lauritz_forum_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
