DLauritz\Forum\UserBundle\Entity\User:
  type: entity
  table: users
  id:
    id:
      type: bigint
      generator: { strategy: AUTO }
  fields:
    email:
      type: string
    password:
      type: string
    display_name:
      type: string
      default: ''
    rank:
      type: integer
      default: 1 # 1=user, 2=admin, 3=sysop (0=guest)
    avatar:
      type: string
      default: ''
    timezone:
      type: string
      default: ''
    bio:
      type: text
      default: ''
    joined:
      type: datetime
    verified:
      type: boolean
      default: false
    authcode:
      type: string
      nullable: true
  oneToMany:
    posts:
      targetEntity: DLauritz\Forum\ContentBundle\Entity\Post
      mappedBy: creator