security:
    encoders:
        DLauritz\Forum\UserBundle\Entity\User: sha512

    providers:
        main:
            entity: { class: DLauritz\Forum\UserBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_area:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
            anonymous: ~
            remember_me:
                key: %secret%
                lifetime: 84600
                path: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
