register:
  pattern: /register
  defaults:
    _controller: DLauritzForumUserBundle:User:register
    _format: html

register_check:
  pattern: /register/save
  defaults:
    _controller: DLauritzForumUserBundle:User:registerCheck
    _format: html

user_profile:
  pattern: /user/{id}.{_format}
  defaults:
    _controller: DLauritzForumUserBundle:User:profile
    _format: html
  requirements:
    _format: html|json