register:
  pattern: /register
  defaults:
    _controller: DLauritzForumUserBundle:User:register
    _format: html

register_check:
  pattern: /register/save
  defaults:
    _controller: DLauritzForumUserBundle:User:registerCheck
    _format: html

user_profile:
  pattern: /user/view/{id}.{_format}
  defaults:
    _controller: DLauritzForumUserBundle:User:profile
    _format: html
  requirements:
    _format: html|json

user_verify:
  pattern: /user/verify/{id}/{authcode}
  defaults:
    _controller: DLauritzForumUserBundle:User:authorize

user_edit:
  pattern: /user/edit/{id}
  defaults:
    _controller: DLauritzForumUserBundle:User:edit
    _format: html
