
# Username:
# Starts and ends with a word character, but has
# word characters, spaces, or underscores in-between

DLauritz\Forum\UserBundle\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: email, message: "That email address is already in use." }
  properties:
    email:
      - Email: ~
    password:
      - NotBlank: { groups: [registration] }
      - MinLength: { limit: 6, message: "Password must be at least 6 characters long" }