parameters:
#    d_lauritz_forum_help.example.class: DLauritz\Forum\HelpBundle\Example

services:
#    d_lauritz_forum_help.example:
#        class: %d_lauritz_forum_help.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
